version: '3.0'
services:

  alpine: &base
    build:
      context: .
      dockerfile: alpine/latest/Dockerfile
    volumes:
      - .:/workingdir
    tty: true
    stdin_open: true
    entrypoint: ["/bin/sh"]
    working_dir: "/workingdir"

  amazonlinux:
    <<: *base
    build:
      context: .
      dockerfile: amazonlinux/latest/Dockerfile

  centos:
    <<: *base
    build:
      context: .
      dockerfile: centos/latest/Dockerfile

  centos-edge:
    <<: *base
    build:
      context: .
      dockerfile: centos/edge/Dockerfile

  centos6:
    <<: *base
    build:
      context: .
      dockerfile: centos/centos6/Dockerfile

  centos7:
    <<: *base
    build:
      context: .
      dockerfile: centos/centos7/Dockerfile

  clearlinux:
    <<: *base
    build:
      context: .
      dockerfile: clearlinux/latest/Dockerfile

  crux:
    <<: *base
    build:
      context: .
      dockerfile: crux/latest/Dockerfile

  oraclelinux:
    <<: *base
    build:
      context: .
      dockerfile: oraclelinux/latest/Dockerfile

  photon:
    <<: *base
    build:
      context: .
      dockerfile: photon/latest/Dockerfile

  sl:
    <<: *base
    build:
      context: .
      dockerfile: sl/latest/Dockerfile

  sourcemage:
    <<: *base
    build:
      context: .
      dockerfile: sourcemage/latest/Dockerfile

  ubuntu:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/latest/Dockerfile

  ubuntu-cosmic:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/cosmic/Dockerfile

  ubuntu-edge:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/edge/Dockerfile

  ubuntu-trusty:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/trusty/Dockerfile

  ubuntu-xenial:
    <<: *base
    build:
      context: .
      dockerfile: ubuntu/xenial/Dockerfile